### ISSUE TITLE
Electrical enginnering video resources and books

### ISSUE THREAD

**Issue by 200901002** [SergioGasquez/awesome-electronic-engineering#9]
https://explore.airgapflux.in/

https://airgapflux.in/

Hey, I made a website where I have collected some electrical (power and energy) and electronic engineering (+control and DSP) resources.

I would like the maintainers of this repo to take a look and see if it’s worth adding to your list.

Humbly, Adhithya

**Comment by SergioGasquez** [comment]
Hi! Just peeked at the content and I think it's a worthy addition. Thanks for gathering the list, would you mind opening a PR?

**Comment by 200901002** [comment]
Thank you, I have just completed it. Please feel free to edit it or place it in the right location if you think it's necessary.
